#!/usr/bin/env python3
"""Generate a FastHenry2 input deck from Example 12 conductor-network export.

This script uses the Example 12 generator's `--export_centerlines` output to
avoid fragile STEP/STL conversion.

What it generates
- One conductor (single polyline of segments) for the full series path.
- One `.external` between IN and OUT terminals.

Important modeling note
FastHenry computes *partial inductances* unless you include an explicit return
path (e.g., a modeled return conductor or ground plane). The `.external` here
is a convenient starting point for per-helix L/R extraction, but it is not a
complete “loop inductance” unless you model the return.

Example:
  ./scripts/bfem_fasthenry.py --out-inp /tmp/bfem.inp --numPairs 10 --vertTurns 15 --wireWidth 1.0 --wireGap 0.2

Then run FastHenry2 (on Linux Mint is recommended):
  fasthenry /tmp/bfem.inp
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Tuple


@dataclass(frozen=True)
class Point3:
    x_mm: float
    y_mm: float
    z_mm: float


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _run_export_conductor_network(args: argparse.Namespace, json_path: Path) -> None:
    repo = _repo_root()

    cmd = [
        "moon",
        "run",
        "--target",
        "native",
        "examples/12-bifilar-electromagnet",
        "--",
        "--export_conductor_network",
        str(json_path),
        "--nocoil" if args.nocoil else "",
        "--nocage" if args.nocage else "",
        "--nowires" if args.nowires else "",
        "--nosupport" if args.nosupport else "",
        "--numPairs",
        str(args.numPairs),
        "--vertTurns",
        str(args.vertTurns),
        "--wireWidth",
        str(args.wireWidth),
        "--wireGap",
        str(args.wireGap),
        "--innerDiam",
        str(args.innerDiam),
        "--numSegs",
        str(args.numSegs),
    ]
    cmd = [c for c in cmd if c]

    proc = subprocess.run(
        cmd,
        cwd=str(repo),
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        raise SystemExit(proc.returncode)


def _mm_to_m(mm: float) -> float:
    return mm * 1.0e-3


def _load_centerlines(path: Path) -> Dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("schema") != "bfem:conductor-network:v1":
        raise ValueError(f"Unexpected schema: {data.get('schema')}")
    if data.get("units") != "mm":
        raise ValueError(f"Unexpected units: {data.get('units')}")
    return data


def _sanitize_name(name: str) -> str:
    # FastHenry node/seg names are simplest if alnum+underscore.
    out = []
    for ch in name:
        if ch.isalnum():
            out.append(ch)
        else:
            out.append("_")
    s = "".join(out)
    return s[:40] if len(s) > 40 else s


def _format_float(v: float) -> str:
    # Use a stable scientific-ish format.
    return f"{v:.12g}"


def build_fasthenry_deck(
    data: Dict[str, Any],
    sigma_s_per_m: float,
    nhinc: int,
    nwinc: int,
    fmin_hz: float,
    fmax_hz: float,
    ndec: int,
) -> str:
    cs = data.get("cross_section", {})
    width_mm = float(cs.get("width_mm"))
    w_m = _mm_to_m(width_mm)
    h_m = w_m

    lines: List[str] = []
    lines.append("* bfem FastHenry2 deck generated by scripts/bfem_fasthenry.py")
    lines.append(".units m")
    lines.append(
        f".default sigma={_format_float(sigma_s_per_m)} w={_format_float(w_m)} h={_format_float(h_m)} nhinc={nhinc} nwinc={nwinc}"
    )
    lines.append("")

    paths = data.get("paths", [])
    if not isinstance(paths, list) or not paths:
        raise ValueError("No paths found in conductor-network JSON")
    path = paths[0]
    name = str(path.get("name", "bfem:conductor:series"))
    safe = _sanitize_name(name)
    pts = path.get("points")
    if not isinstance(pts, list) or len(pts) < 2:
        raise ValueError("Series path must have at least 2 points")

    node_names: List[str] = []
    for i, p in enumerate(pts):
        x_mm, y_mm, z_mm = float(p[0]), float(p[1]), float(p[2])
        node = f"N_{safe}_{i}"
        node_names.append(node)
        lines.append(
            f"{node} x={_format_float(_mm_to_m(x_mm))} y={_format_float(_mm_to_m(y_mm))} z={_format_float(_mm_to_m(z_mm))}"
        )

    for i in range(1, len(node_names)):
        seg = f"E_{safe}_{i-1}_{i}"
        lines.append(f"{seg} {node_names[i-1]} {node_names[i]}")

    # Single external between endpoints. Exporter ensures endpoints correspond
    # to IN and OUT terminal points.
    lines.append("")
    lines.append(f".external {node_names[0]} {node_names[-1]} BFEM_IN_OUT")

    lines.append(
        f".freq fmin={_format_float(fmin_hz)} fmax={_format_float(fmax_hz)} ndec={ndec}"
    )
    lines.append(".end")
    lines.append("")

    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Generate a FastHenry2 deck for BFEM helix centerlines.")

    # Mirror key MoonBit args.
    p.add_argument("--innerDiam", type=float, default=6.0)
    p.add_argument("--numPairs", type=int, default=10)
    p.add_argument("--numSegs", type=int, default=36)
    p.add_argument("--vertTurns", type=float, default=15.0)
    p.add_argument("--wireWidth", type=float, default=1.0)
    p.add_argument("--wireGap", type=float, default=0.2)

    p.add_argument("--nocoil", action="store_true")
    p.add_argument("--nocage", action="store_true")
    p.add_argument("--nowires", action="store_true")
    p.add_argument("--nosupport", action="store_true")

    p.add_argument("--out-inp", type=Path, required=True, help="Output FastHenry .inp file")

    # FastHenry parameters
    p.add_argument(
        "--sigma",
        type=float,
        default=5.8e7,
        help="Conductivity (S/m). Default is copper-ish.",
    )
    p.add_argument("--nhinc", type=int, default=1, help="Filament subdivisions in height")
    p.add_argument("--nwinc", type=int, default=1, help="Filament subdivisions in width")

    p.add_argument("--fmin", type=float, default=1.0, help="FastHenry fmin (Hz)")
    p.add_argument("--fmax", type=float, default=1.0, help="FastHenry fmax (Hz)")
    p.add_argument("--ndec", type=int, default=1, help="FastHenry points per decade")

    return p


def main() -> None:
    args = build_parser().parse_args()

    with tempfile.TemporaryDirectory(prefix="bfem_centerlines_") as td:
        json_path = Path(td) / "centerlines.json"
        _run_export_conductor_network(args, json_path)
        data = _load_centerlines(json_path)

    deck = build_fasthenry_deck(
        data,
        sigma_s_per_m=args.sigma,
        nhinc=args.nhinc,
        nwinc=args.nwinc,
        fmin_hz=args.fmin,
        fmax_hz=args.fmax,
        ndec=args.ndec,
    )
    args.out_inp.write_text(deck, encoding="utf-8")
    print(f"Wrote: {args.out_inp}")
    print("Note: This deck defines a single .external between BFEM IN/OUT.")


if __name__ == "__main__":
    main()
